server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    encoding: UTF-8
    basename: messages/message
  data:
    redis:
      host: 192.168.1.188
      port: 6379
#      cluster:
#        nodes:
#          - 192.168.57.135:7001
#          - 192.168.57.135:7002
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接

thread:
  corePoolSize: 10
  maxPoolSize: 500
  keepAliveSeconds: 60
  queueCapacity: 500
  threadNamePrefix: Executor-

basecontext:
  exclude:
    - /user/login
    - /user/logout

logging:
  #config: classpath:logback.xml
  level:
    root: info
    com.wj.demo: debug
  file:
    path: D:/logs

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
