server:
  port: 8080
  servlet:
    context-path: /
  undertow:
    #  POST请求内容的最大大小。当值为-1时，默认值为大小是无限的
    max-http-post-size: -1B

spring:
  web:
    resources:
      #静态资源映射
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # JavaMailSender Config
  mail:
    host: smtp.163.com
    port:
    username: wangjian178321@163.com
    password: OZXPXUHCTZATGAWG
  messages:
    encoding: UTF-8
    basename: messages/message
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
    #      cluster:
    #        nodes:
    #          - 192.168.57.135:7001
    #          - 192.168.57.135:7002
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    ##确认消息从生产者到交换机
    publisher-confirm-type: correlated
    ##确认消息从交换机到队列
    publisher-returns: true
    ##消费者
    listener:
      simple:
        ##消费者一次消费的消息数量
        prefetch: 5
        ##消费者手动确认模式
        acknowledge-mode: manual
thread:
  corePoolSize: 10
  maxPoolSize: 500
  keepAliveSeconds: 60
  queueCapacity: 500
  threadNamePrefix: Executor-

springdoc:
  swagger-ui:
    # 是否开启swagger
    enabled: true
    # 访问路径
    path: /swagger-ui.html
    # 显示标签排序
    tags-sorter:  alpha
    # 禁用示例接口
    disable-swagger-default-url: true
  api-docs:
    # 开启 OpenAPI 展示
    enabled: true
    # UI访问路径
    path: /v3/api-docs
  # 文档包含的路径
#  packages-to-scan:

#spring boot actuator配置
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        # 暴露的端点 默认是/actuator/health
        include: health
      base-path: /actuator

#mybatis-flex配置
mybatis-flex:
  mapper-locations: classpath*:/mapper/**/*.xml
  datasource:
    # 主库数据源
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/demo
      username: root
      password: root
      druid:
        validation-query: SELECT 1 FROM DUAL
      # 从库数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/demo
        username: root
        password: root
        druid:
          validation-query: SELECT 1 FROM DUAL

#日志配置
logging:
  #config: classpath:logback.xml
  level:
    root: info
    com.wj.demo: debug
  file:
    path: D:/logs

#系统配置
system:
  #登录登出配置
  security:
    loginHandler: default
    logoutHandler: default
    loginUrl: /formLogin
    loginPage: /loginPage
    logoutUrl: /logout
    expireTime: 86400
    #最少32位的密钥
    secretKey: 123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
    #接口权限忽略接口
    auth:
      exclude:
        - /actuator/health
  request:
    allowed-referer:
      referer:
        - http://localhost:8080
        - http://localhost:8081
  #国际化忽略接口
  i18n:
    exclude:
  #文件上传
  file:
    # 环境变量优先，不存在则用默认值
    upload-path: ${SYSTEM_FILE_UPLOAD_PATH:D:\upload}

# 企业微信
wechat:
  # 企业id
  corpId: ww41dd9ec8de52f188
  # 企业密钥
  corpSecret: UKtzKvjp3NPsmIxSbNufTok8VaXyQ5d01aKcnCeMU-U
  # 应用密钥
  encodingAESKey: ABC1234567890123456789012345678901234567890
  # 应用ID todo后面支持多个应用ID
  agentId: 1000002
  # 获取token的url
  tokenUrl: https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=%s&corpsecret=%s
  # 发送消息的url
  messageUrl: https://qyapi.weixin.qq.com/cgi-bin/message/send?debug=1&access_token=%s
  # 上传临时素材url
  uploadUrl: https://qyapi.weixin.qq.com/cgi-bin/media/upload?access_token=%s&type=%s
  # 上传图片url
  uploadImageUrl: https://qyapi.weixin.qq.com/cgi-bin/media/uploadimg?access_token=%s
  # 企业微信机器人 todo 后面支持配置多个机器人
  robotUrl: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=4ef79eb2-8b00-4ef9-a014-832a5ef93d8e