server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

basecontext:
  exclude:
    - /user/login
    - /user/logout
