server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    encoding: UTF-8
    basename: messages/message

basecontext:
  exclude:
    - /user/login
    - /user/logout

logging:
  #config: classpath:logback.xml
  level:
    root: info
    com.wj.demo: debug
  file:
    path: D:/logs

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
